// Workout data — mirrors docs/workout.md. Sequence matters: do not reorder.

const BLOCKS = {
  warmup:  { name: 'Warm-up',    color: '#0033e6', ink: '#ffffff' },
  legs:    { name: 'Legs',       color: '#e30613', ink: '#ffffff' },
  core:    { name: 'Core',       color: '#ffc800', ink: '#0a0a0a' },
  upper:   { name: 'Upper body', color: '#0a0a0a', ink: '#ffffff' },
  stretch: { name: 'Stretch',    color: '#00764a', ink: '#ffffff' },
};

// Each exercise: block, name, scheme (what to do), restBefore (seconds),
// description, trains, and for timed work: segments [{label, seconds}].
const EXERCISES = [
  {
    block: 'warmup',
    name: 'Jog in place, arms circling forward',
    scheme: '1 minute',
    restBefore: 0,
    segments: [{ label: '', seconds: 60 }],
    description: 'Quick small steps on your toes. Arms stretched out to the sides, rotating in small forward circles the whole time.',
    trains: 'Shoulders, calves, pulse up',
  },
  {
    block: 'warmup',
    name: 'Jog in place, arms circling backward',
    scheme: '1 minute',
    restBefore: 5,
    segments: [{ label: '', seconds: 60 }],
    description: 'Same as before — quick steps on your toes — but rotate the straight arms in backward circles.',
    trains: 'Shoulders, calves',
  },
  {
    block: 'warmup',
    name: 'Single-leg hops, band in front',
    scheme: '30 sec per leg',
    restBefore: 10,
    segments: [
      { label: 'Left leg', seconds: 30 },
      { label: 'Right leg', seconds: 30 },
    ],
    description: 'Hop in place on the toes of one foot. Hold the band stretched between both hands in front of you at shoulder height, arms spread, keeping tension.',
    trains: 'Balance, calves, shoulders',
  },
  {
    block: 'warmup',
    name: 'Single-leg hops, band overhead',
    scheme: '30 sec per leg',
    restBefore: 10,
    segments: [
      { label: 'Left leg', seconds: 30 },
      { label: 'Right leg', seconds: 30 },
    ],
    description: 'Same hops, but hold the band overhead with arms spread, keeping it under tension.',
    trains: 'Balance, calves, shoulders',
  },
  {
    block: 'legs',
    name: 'Bulgarian split squats',
    reps: '2 × 15',
    scheme: '2 × 15 per side',
    restBefore: 45,
    description: 'Back foot up on the couch behind you, front leg does the work. Lower until the front thigh is parallel to the floor, torso upright, then drive up through the front heel. All reps one side, then switch.',
    trains: 'Quads, glutes, balance',
  },
  {
    block: 'legs',
    name: 'Single-leg hip thrusts',
    reps: '2 × 15',
    scheme: '2 × 15 per side',
    restBefore: 45,
    description: 'On your back, knees bent. Lift one foot and extend that leg. Drive through the planted heel until shoulders–hips–knee form a line. Squeeze at the top, lower with control.',
    trains: 'Glutes, hamstrings',
  },
  {
    block: 'legs',
    name: 'Single-leg Romanian deadlifts',
    reps: '2 × 10',
    scheme: '2 × 10 per side',
    restBefore: 45,
    description: 'Stand on one leg, soft knee, kettlebell in the opposite hand. Hinge at the hip — push the hips back, free leg extends behind you — until the standing hamstring stretches. Back flat. Squeeze the glute to stand up.',
    trains: 'Hamstrings, glutes, balance',
  },
  {
    block: 'legs',
    name: 'Side-lying leg raises',
    reps: '1 × 20',
    scheme: '20 per side · band at ankles',
    restBefore: 30,
    description: 'Band around both ankles. Lie on your side, body straight, legs stacked. Lift the top leg straight up against the band, toes pointing forward, lower with control.',
    trains: 'Outer hip, glute medius',
  },
  {
    block: 'legs',
    name: 'Squats',
    reps: '1 × 20',
    scheme: '1 × 20',
    restBefore: 30,
    description: 'Feet shoulder-width, toes slightly out. Sit back and down, heels planted, chest up, thighs to parallel. Drive up through the heels.',
    trains: 'Quads, glutes',
  },
  {
    block: 'core',
    name: 'Plank with leg raises',
    scheme: '2 × 45 sec',
    restBefore: 45,
    segments: [
      { label: 'Set 1', seconds: 45 },
      { label: 'Set 2', seconds: 45 },
    ],
    description: 'Forearm plank, body in one line, core braced. Lift one leg a few centimeters, set it down, lift the other — alternating quickly for the full time. No sagging hips.',
    trains: 'Deep core, glutes',
  },
  {
    block: 'core',
    name: 'Side planks',
    scheme: '2 × 30 sec per side',
    restBefore: 30,
    segments: [
      { label: 'Set 1 · left', seconds: 30 },
      { label: 'Set 1 · right', seconds: 30 },
      { label: 'Set 2 · left', seconds: 30 },
      { label: 'Set 2 · right', seconds: 30 },
    ],
    description: 'Lie on your side, forearm under the shoulder, body in one straight line. Lift the hips and hold — no sagging, no twisting forward. This is what keeps your hips steady when climbing out of the saddle.',
    trains: 'Obliques, lateral core, glute medius',
  },
  {
    block: 'core',
    name: 'Jackknives with band',
    reps: '2 × 15',
    scheme: '2 × 15',
    restBefore: 30,
    description: 'Flat on your back, legs straight, arms overhead holding the band spread under tension. Fold in half — straight legs and torso rise to meet — then lower with control. Keep band tension throughout.',
    trains: 'Abs, hip flexors, shoulders',
  },
  {
    block: 'core',
    name: 'Russian twists',
    reps: '1 × 20',
    scheme: '1 × 20 · 4 kg kettlebell',
    restBefore: 30,
    description: 'Seated, knees bent, feet light or lifted, torso leaned back 45°. Kettlebell at your chest — rotate it to one hip, then all the way to the other. Twist from the waist, not the arms.',
    trains: 'Obliques, rotation',
  },
  {
    block: 'upper',
    name: 'Knee pushups on fists',
    reps: '2 × 15',
    scheme: '2 × 15',
    restBefore: 45,
    description: 'Fists on the floor shoulder-width, knuckles down, wrists straight. Body in one line head to knees. Chest to just above the floor, elbows at 45°, press back up.',
    trains: 'Chest, triceps, front delts',
  },
  {
    block: 'upper',
    name: 'Seated band rows',
    reps: '2 × 15',
    scheme: '2 × 15',
    restBefore: 30,
    description: 'Sit with legs extended, band looped around your feet, one end per hand. Sit tall and pull to the lower ribs, elbows driving back, shoulder blades squeezing together. Release with control.',
    trains: 'Lats, mid-back, biceps',
  },
  {
    block: 'upper',
    name: 'Superman hold with band',
    scheme: '45 sec',
    restBefore: 30,
    segments: [{ label: '', seconds: 45 }],
    description: 'Face down, fully stretched, arms straight ahead holding the band spread under tension. Lift arms, chest and legs off the floor and hold. Band stays taut.',
    trains: 'Lower back, rear delts',
  },
  {
    block: 'upper',
    name: 'Prone arm circles',
    reps: '1 × 15',
    scheme: '1 × 15',
    restBefore: 30,
    description: 'Face down, arms straight ahead, thumbs up, chest slightly lifted. Sweep both arms in a wide symmetrical arc from overhead down to your hips and back — a slow breaststroke, arms never touching the floor.',
    trains: 'Rear delts, traps, mobility',
  },
  {
    block: 'stretch',
    name: 'Lying hamstring stretch',
    scheme: '50 sec per leg · with band',
    restBefore: 20,
    segments: [
      { label: 'Left leg', seconds: 50 },
      { label: 'Right leg', seconds: 50 },
    ],
    description: 'On your back, band around the sole of one foot, leg straight up. Gently pull the leg toward you until the back of the thigh clearly stretches. Breathe slowly — it deepens on the exhale.',
    trains: 'Hamstrings',
  },
  {
    block: 'stretch',
    name: 'Seated forward fold',
    scheme: '40 sec per leg',
    restBefore: 10,
    segments: [
      { label: 'Left leg', seconds: 40 },
      { label: 'Right leg', seconds: 40 },
    ],
    description: 'One leg straight, the other foot against its inner thigh. Hinge forward from the hips with a long back — chest toward the toes, no rounding — and hold where the hamstring stretches.',
    trains: 'Hamstrings',
  },
  {
    block: 'stretch',
    name: 'Kneeling hip flexor stretch',
    scheme: '45 sec per side',
    restBefore: 10,
    segments: [
      { label: 'Left side', seconds: 45 },
      { label: 'Right side', seconds: 45 },
    ],
    description: 'Kneel on one knee (cushion under it), other foot planted ahead. Tuck the pelvis under first, then shift gently forward until the front of the rear hip stretches. Squeeze the rear glute. Counters the hours of hip flexion on the bike.',
    trains: 'Hip flexors, psoas',
  },
  {
    block: 'stretch',
    name: 'Downward dog',
    scheme: '45 sec',
    restBefore: 10,
    segments: [{ label: '', seconds: 45 }],
    description: 'Hips up and back into an upside-down V. Pedal the heels toward the floor one at a time. Knees slightly bent is fine — a long straight back beats straight legs.',
    trains: 'Hamstrings, calves',
  },
];
